--create table Books (
--	Id int not null identity primary key,
--	Title nvarchar(255) not null,
--	Author nvarchar(100) not null,
--	[Year] int,
--	Copies int default 1
--)

insert into Books (Title, Author, [Year], Copies)
values ('Harry Potter and the Philosopher''s Stone', 'J. K. Rowling', 1997, 8)
insert into Books (Title, Author, [Year], Copies)
values ('Harry Potter and the Chamber of Secrets', 'J. K. Rowling', 1998, 3)
insert into Books (Title, Author, [Year], Copies)
values ('Harry Potter and the Prisoner of Azkaban', 'J. K. Rowling', 1999, 24)
insert into Books (Title, Author, [Year])
values ('Harry Potter and the Goblet of Fire', 'J. K. Rowling', 2000)
insert into Books (Title, Author, [Year], Copies)
values ('Harry Potter and the Half-Blood Prince', 'J. K. Rowling', 2005, 18)
insert into Books (Title, Author, [Year], Copies)
values ('Harry Potter and the Deathly Hallows', 'J. K. Rowling', 2007, 10)
insert into Books (Title, Author, [Year], Copies)
values ('The Sound Pattern of Russian', 'Morris Halle', 1958, 15)
insert into Books (Title, Author, [Year], Copies)
values ('Syntactic Structures', 'Noam Chomsky', 1959, 5)
insert into Books (Title, Author, [Year])
values ('Elements of Acoustic Phonetics', 'Peter Ladefoged', 2003)
insert into Books (Title, Author, [Year])
values ('A Course in Phonetics', 'Peter Ladefoged', 1995)
insert into Books (Title, Author, [Year], Copies)
values ('Phonetic Data Analysis: An Introduction to Instrumental Phonetic Fieldwork', 'Peter Ladefoged', 2004, 2)
insert into Books (Title, Author, [Year])
values ('Shrinking Violets: A Field Guide to Shyness', 'Joe Moran', 2014)
insert into Books (Title, Author, [Year], Copies)
values ('Frankenstein; or, The Modern Prometheus', 'Mary Shelly', 1818, 11)
insert into Books (Title, Author, [Year], Copies)
values ('Born a Crime', 'Trevor Noah', 2016, 12)
insert into Books (Title, Author, [Year])
values ('Wheels of Change: How the Bicycle Empowered Women', 'Sue Macy', 2011)
insert into Books (Title, Author, [Year], Copies)
values ('The Language of New Media', 'Lev Manovich', 2001, 35)
insert into Books (Title, Author, [Year], Copies)
values ('The Neverending Story', 'Michael Ende', 1973, 10)
insert into Books (Title, Author, [Year])
values ('Howl''s Moving Castle', 'Diana Wynne Jones', 1986)
insert into Books (Title, Author, [Year], Copies)
values ('The Hobbit, or There and Back Again', 'J. R. R. Tolkien', 1937, 17)
insert into Books (Title, Author, [Year], Copies)
values ('Pippi Longstocking', 'Astrid Lindgren', 1945, 4)
insert into Books (Title, Author, [Year], Copies)
values ('Comet in Moominland', 'Tove Jansson', 1946, 11)
insert into Books (Title, Author, [Year], Copies)
values ('Moominsummer Maddness', 'Tove Jansson', 1940, 5)
insert into Books (Title, Author, [Year])
values ('Moominland Midwinter', 'Tove Jansson', 1941)
insert into Books (Title, Author, [Year])
values ('Moominvalley in November', 'Tove Jansson', 1939)
insert into Books (Title, Author, [Year], Copies)
values ('Murder on the Orient Express', 'Agatha Christie', 1933, 13)
insert into Books (Title, Author, [Year], Copies)
values ('Death on the Nile', 'Agatha Christie', 1928, 10)
insert into Books (Title, Author, [Year], Copies)
values ('The Murder of Roger Ackroyd', 'Agatha Christie', 1929, 9)
insert into Books (Title, Author, [Year], Copies)
values ('Mio, My Son', 'Astrid Lindgren', 1951, 4)
insert into Books (Title, Author, [Year], Copies)
values ('Dune', 'Frank Herbert', 1965, 2)
