create table Topics (
	TopicId int not null identity primary key,
	TopicName nvarchar(20) not null 
)

insert into Topics (TopicName) values ('Latvia')
insert into Topics (TopicName) values ('World')
insert into Topics (TopicName) values ('Culture')
insert into Topics (TopicName) values ('Business')
insert into Topics (TopicName) values ('Crime')
insert into Topics (TopicName) values ('Sport')

create table Articles (
	ArticleId int not null primary key identity,
	TopicId int foreign key references Topics(TopicId),
	Headline nvarchar(255) not null,
	Author nvarchar(255) default 'The Daily Prophet editorial staff',
	Body nvarchar(2000) not null,
	WhenAdded datetime default getdate()
)

select * from Articles

insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (1, 'Riga has good chances to host Quidditch World Cup 2025', 'Ludo Bagman', 'At a press conferece today, January 13th 2021, the President of Latvia Quidditch Federation Ruta Knupite has announced that Riga has officially entered the competition to host Quidditch World Cup 2025. As anonymous source in World Quidditch Federation told our reporter, the chances are quite high for our fair city to host the greatest sports event of the year.', '2021-01-13 13:15:03')

insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (1, 'Latvia in Top 5 of best countries for wizard start-ups', 'Betty Braithwaite', 'According to Wizarding Business Review, it is the first time Latvia has made Top 5 of the best countries for wizard start-ups. Three fctor were evaluated: investment climate, tax policy and the cuteness level of local kitties (needless to say, Latvian kitties are the cutest!). Great news for local business!', '2021-02-26 21:01:56')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (5, 'Telegram refuses to ban Death Eaters'' channels', 'Dempster Wiggleswade', 'Telegram refuses to ban Death Eaters'' channels', '2021-02-28 12:00:39')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (5, 'You-Know-Who thought to be behind The Wizard Bulletin fake news portal', 'Zamira Gulch', 'You-Know-Who thought to be behind The Wizard Bulletin fake news portal', '2021-02-18 11:05:11')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (5, 'Beware: Fake Deathly Hallows replicas have swarmed the market', 'Dempster Wiggleswade', 'Beware: Fake Deathly Hallows replicas have swarmed the market', '2021-02-20 19:37:30')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (5, 'Lucius Malfoy wanted for illegal hairdresser visit', 'Dempster Wiggleswade', 'Lucius Malfoy wanted for an illegal hairdresser visit', '2021-02-15 20:02:16')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (2, 'Longing for travel: Top 10 destinations for a short flying Ford Anglia trip', 'Zamira Gulch', 'Longing for travel: Top 10 destinations for a short flying Ford Anglia trip', '2021-02-04 06:08:10')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (2, 'The Heir of Slytherin to start school at Hogwarts this autumn', 'Zamira Gulch', 'The Heir of Slytherin to start school at Hogwarts this autumn', '2021-01-27 10:00:19')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (2, 'Breaking: The Dark Lord is back!', 'Barnabas Cuffe', 'Breaking: The Dark Lord is back!', '2021-02-13 06:06:06')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (2, 'Harry Potter tops The Wizards Magazine 20 Under 20 2020 List', 'Barnabas Cuffe', 'Harry Potter tops The Wizards Magazine 20 Under 20 2020 List', '2021-02-11 12:19:02')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (6, 'Five experts, five broomsticks. Which one an aspiring quidditch world champion should go for?', 'Ludo Bagman', 'It takes only a time turner to gather five legendary quidditch players in one room. Catriona McCormack, Gwendolyn Morgan, Dai Llewellyn, Viktor Krum and Barberus Bragge try the latest broomstick models. Which one an aspiring quidditch world champion should go for', '2021-02-23 12:01:01')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (6, 'First ever Wizard Chess World Championship to take place in 2022', 'Ludo Bagman', 'First ever Wizard Chess World Championship to take place in 2022', '2021-02-25 13:14:13')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (6, 'Good news for quidditch players: New Nimbus 2021 finally out!', 'Ludo Bagman', 'Good news for quidditch players: New Nimbus 2021 finally out!', '2021-02-03 09:42:15')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (6, 'Exclusive: Viktor Krum revisits historical Bulgaria victory', 'Ludo Bagman', 'In this exclusive interview to our sports reporter Ludo Bagman, the legendary Bulgarian seeker Viktor Krum talks life, sport and challenges of raising a new generation of quidditch players.', '2021-02-21 17:17:40')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (6, 'Dungeons and Dragons: The lame muggle game redefined', 'Ludo Bagman', 'Dungeons and Dragons: The lame muggle game redefined', '2021-02-14 14:10:01')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (3, 'Do muggles rock? Exploring muggle music', 'Rita Skeeter', 'Do muggles rock? Exploring muggle music', '2021-02-19 07:57:51')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (3, 'Heads over heels: Nearly Headless Nick on finding true love at 500', 'Rita Skeeter', 'Heads over heels: Nearly Headless Nick on finding true love at 500', '2021-02-16 11:19:31')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (3, 'Hogwarts presents free online learning platform', 'Rita Skeeter', 'Hogwarts presents free online learning platform', '2021-02-24 15:15:00')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (4, 'Hogwarts Railways acquires Peter Boat', 'Barnabas Cuffe', 'It was announced today that Hogwarts Railways has acquired the Peter Boat Company. The Board is hoping to continue expanding by entering maritime traffic industry.', '2021-02-12 09:23:06')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (4, 'Hogwarts Railways expands to France', 'Zamira Gulch', 'It is became known today that Hogwarts Railways expands to France by establishing new Calais–Hogwarts line. As experts predict, it can enhance competition in the famous school of witchcraft and wizardry, as more foreign students will be able to attend.', '2021-02-10 10:00:17')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (4, 'It''s official: Royal Star Steam Co. goes public', 'Zamira Gulch', 'It''s official: Royal Star Steam Co. goes public, the company president has announced this morning right before the opening of the Stock Exchange. As of today, anyone interested will be able to buy Royal Star Steam Co. shares.', '2021-01-30 11:11:11')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (4, 'Madam Malkin''s Robes for All Occasions to open a showroom in Riga', 'Zamira Gulch', 'Great news for all the witches and wizards in Riga: Madam Malkin''s Robes for All Occasions will open a showroom here just in a couple of months. At the moment, opening is planned for early May. The showroom will be located on Miera Street: Madam Malkin thinks — quite rightfully — it will blend in perfectly, as well as will definitely seize the opportuity to capitalize on the account of muggle hipsters of the area.', '2021-02-07 09:05:00')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (4, 'Honeydukes announces new vegan product line', 'Zamira Gulch', 'Great news for all the vegan wizards and witches out there! Honeydukes announces new vegan product line. Every Flavour Beans, Fizzing Whizzbees, Chocolate Frogs, Drooble''s Best Blowing Gum and other sweets from now on without dairy or other animal ingredients.', '2021-02-11 06:00:01')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (3, 'The Vampire from the Valleys: Interview with Blodwyn Bludd', 'Zamira Gulch', 'In this exclusive interview, Blodwyn Bludd talks his music, as well as opens up about the struggles of a vampire and his love story with a werewolf.', '2021-01-28 12:00:39')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (3, 'The Wizarding Wireless Network Top 100 of 2020', 'Rita Skeeter', 'The Wizarding Wireless Network hae published their Top 100 of 2020. Do you want to know who made it? Listen to our special Spotify playlist!', '2020-12-31 16:11:33')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (5, '400 l of polyjuice potion confiscated on Belarus–Latvia border', 'Dempster Wiggleswade', 'The night is dark and full of terrors. In the night of February 25, a group of muggle smugglers arrested on Latvia—Belarus border with 400 l of polyjuice potion. It is the largest illegal polyjuice freight confiscated in recorded history. Investigation pending. Follow us for the latest news!', '2021-02-25 10:14:21')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (5, 'Death Eaters go online: Cyber crime is rising during pandemic', 'Dempster Wiggleswade', 'As pandemic expands and traveling restrictions tighten, Death Eaters move online to keep working on their dark mission to bring back You-Know-Who. Beware, cyber crime is on the rise, the wizard police spokesperson has informed the press during special press conference this morning.', '2021-02-27 23:35:47')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (2, 'Latest news from the W8 summit: The most powerful wizards meet in London', 'Zamira Gulch', 'This week, the W8 summit is taking place in London. Eight most powerful wizards of the world discuss global affairs. Check out our live update feed to keep yourself informed!', '2021-01-31 20:01:38')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (2, 'Crime of the century? Gringotts robbed', 'Zamira Gulch', 'Breaking news received today: this morning, the Bank of Gringotts was robbed. Many experts have labelled this audacious act the crime of the century. Investigation pending. Stay tuned for the updates! Our reporters keep their ear to the ground.', '2021-02-13 08:23:23')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (6, 'The Triwizard Tournament 2021 to take place fully online', 'Ludo Bagman', 'On February 27th, The Triwizard Tournament Organizing Committee gave a press conference at the Ministry of Magic Great Conference Hall. The main announcement — for the first time in 700 years, the Tournament will take place fully online using Zoom. Special Virtual Affairs Committee was formed to adapt this inferior muggle technology to wizards'' needs.', '2021-02-27 23:07:59')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (3, 'Hobbies during pandemic: How to create a horcrux at home', 'Tom Marvolo Riddle', 'During these difficult times many of us find it difficult to maintain our beloved hobbies. This guide is for all the horcrux making enthusiasts out there! Our guest author Tom Marvolo Riddle, an experienced horcrux creator, explains how to make your own using items everyone can find at home. Great family time guaranteed!', '2021-02-27 23:15:03')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (4, 'Lean year for mandrake growers, prices have skyrocketed', 'Barnabas Cuffe', 'Due to bad harest, there is significant mandrake shortage across Europe. Although mandrake prices have skyrocketed, growers are struggling. This morning, the Mandrake Growers Association have sent an open letter to the government requesting subsidies to be able to survive until next mandrake crop.', '2021-02-19 10:09:25')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (1, 'Fourteen quidditch players arrested in Daugavpils for breaking lockdown rules', 'Betty Braithwaite', 'Late eveing yesterday, fourteen quidditch players were arrested in Daugavpils for breaking lockdown rules. The illegal game took place by the Stropi lake during curfew. Since the players resisted the wizard police, all of them had to spent the remaining curfew hours in jail.', '2021-02-02 18:00:00')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (1, 'British Minister of Magic visits Riga', 'Winkus Oddpick', 'This week, British Minister of Magic is visiting Riga for the first time in history. Today busy schedule ahead — several meeting with Latvian authorities to discuss the future collaboration between to wizard nations.', '2021-01-25 07:49:00')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (1, 'The Singing Sorceress'' concert in Sigulda cancelled', 'Winkus Oddpick', 'We are sorry to announce that Celestina Warbeck, also known as The Singing Sorceress, has cancelled her concert in Sigulda, which ws long expected by many. The announcement was made as new travel restrictions came into effect. To return your tickets, please contact the organizers.', '2021-01-29 22:37:28')
insert into Articles (TopicId, Headline, Author, Body, WhenAdded) 
values (1, 'Breaking: Sirius Black spotted in Gulbene', 'Barnabas Cuffe', 'BREAKING NEWS: today, the infamous Azkaban escapee Sirius Black was spotted in Gulbene. Please keep your eyes open and, if you see him, please report to the wizard police. And make sure to stock up on chocolate — dementors are coming to town!', '2021-02-27 11:46:01')

alter table Articles add [Image] nvarchar(1000) 